name: Docker image CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      env:
        TAG: ${{ github.ref }}
      run: docker build -t jiangfengming/polyfill-service:${TAG##*/v} -t jiangfengming/polyfill-service:latest .

    - name: Push the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        TAG: ${{ github.ref }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push jiangfengming/polyfill-service:${TAG##*/v}
        docker push jiangfengming/polyfill-service:latest
